/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mmontalvo.vista;

/**
 *
 * @author HP
 */
public class Serie extends javax.swing.JFrame {

    /**
     * Creates new form Serie
     */
    public Serie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        duration_movie = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        id_serie = new javax.swing.JTextField();
        duration_serie = new javax.swing.JTextField();
        creator_serie = new javax.swing.JTextField();
        genre_serie = new javax.swing.JTextField();
        viewed_serie = new javax.swing.JTextField();
        chapter_serie = new javax.swing.JTextField();
        year_serie = new javax.swing.JTextField();
        session_serie = new javax.swing.JTextField();
        title_serie = new javax.swing.JTextField();

        jScrollPane6.setViewportView(duration_movie);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SERIE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 35, -1, -1));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 99, -1, -1));

        jLabel3.setText("TITLE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 130, -1, -1));

        jLabel4.setText("GENRE:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 165, -1, -1));

        jLabel5.setText("CREATOR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 191, -1, -1));

        jLabel6.setText("DURATION:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 217, -1, -1));

        jLabel7.setText("YEAR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 245, -1, -1));

        jLabel8.setText("VIEWED:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 276, -1, -1));

        jLabel9.setText("SESSION QUANTITY:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 302, -1, -1));

        jLabel10.setText("CHAPTER");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 330, -1, -1));

        btnGuardar.setText("GUARDAR");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TITLE", "GENRE", "CREATOR", "DURATION", "YEAR", "VIEWED", "SESSION QUANTITY", "CHAPTER"
            }
        ));
        jScrollPane11.setViewportView(jTable1);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 435, 604, 150));
        getContentPane().add(id_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 96, 140, -1));
        getContentPane().add(duration_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 211, 140, -1));
        getContentPane().add(creator_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 185, 140, -1));
        getContentPane().add(genre_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 159, 140, -1));
        getContentPane().add(viewed_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 273, 140, -1));
        getContentPane().add(chapter_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 324, 140, -1));
        getContentPane().add(year_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 242, 140, -1));
        getContentPane().add(session_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 299, 140, -1));
        getContentPane().add(title_serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 127, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Serie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Serie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField chapter_serie;
    private javax.swing.JTextField creator_serie;
    private javax.swing.JTextPane duration_movie;
    private javax.swing.JTextField duration_serie;
    private javax.swing.JTextField genre_serie;
    private javax.swing.JTextField id_serie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField session_serie;
    private javax.swing.JTextField title_serie;
    private javax.swing.JTextField viewed_serie;
    private javax.swing.JTextField year_serie;
    // End of variables declaration//GEN-END:variables
}
